// AngularFrontend/design-metrics-frontend/src/app/pages/chat-interface/chat-interface.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-chat-interface',
  standalone: true,
  imports: [FormsModule,CommonModule],
  templateUrl: './chat-interface.component.html',
  styleUrls: ['./chat-interface.component.css'],
})
export class ChatInterfaceComponent {
  groups = [
    { id: '1', name: 'Design Team', description: 'Creative professionals' },
    { id: '2', name: 'Development Team', description: 'Tech innovators' },
    { id: '3', name: 'Marketing Team', description: 'Brand storytellers' },
  ];

  userIcons = [
    { name: 'Emma', avatar: '👩‍💻' },
    { name: 'Alex', avatar: '👤' },
    { name: 'Sam', avatar: '🧑‍🎨' },
  ];

  selectedGroup: string | null = null;
  message: string = '';
  messages: Array<{
    groupId: string;
    text: string;
    sender: string;
    timestamp: Date;
  }> = [];
  currentUser = this.userIcons[0];

  get filteredMessages() {
    return this.selectedGroup
      ? this.messages.filter((msg) => msg.groupId === this.selectedGroup)
      : [];
  }

  get selectedGroupName(): string {
    const group = this.groups.find((g) => g.id === this.selectedGroup);
    return group ? group.name : 'Select a Group';
  }

  handleSendMessage(): void {
    if (this.message.trim() && this.selectedGroup) {
      this.messages.push({
        groupId: this.selectedGroup,
        text: this.message,
        sender: this.currentUser.name,
        timestamp: new Date(),
      });
      this.message = '';
    }
  }

  formatTimestamp(date: Date): string {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  }

  handleGroupSelection(groupId: string): void {
    this.selectedGroup = groupId;
  }

  handleUserSelection(user: { name: string; avatar: string }): void {
    this.currentUser = user;
  }
}

<div class="flex h-screen bg-gray-100 overflow-hidden">
    <!-- Sidebar -->
    <div class="w-1/4 bg-white border-r shadow-xl">
      <div class="p-6 bg-gradient-to-r from-blue-600 to-blue-500 text-white">
        <div class="flex items-center space-x-3">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="2"
            stroke="currentColor"
            class="w-8 h-8"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M7 8h10M7 12h6m-9 4h10l2 2m-2-2h3m-3 0v3"
            />
          </svg>
          <h2 class="text-2xl font-bold">Group Chat</h2>
        </div>
      </div>
  
      <div *ngFor="let group of groups" (click)="handleGroupSelection(group.id)" class="p-4 cursor-pointer transition-all duration-200 border-l-4"
           [ngClass]="{
             'border-blue-500 bg-blue-50 text-blue-700': selectedGroup === group.id,
             'border-transparent hover:border-gray-300 hover:bg-gray-50': selectedGroup !== group.id
           }">
        <div class="flex justify-between items-center">
          <div>
            <h3 class="font-semibold text-lg">{{ group.name }}</h3>
            <p class="text-sm text-gray-500">{{ group.description }}</p>
          </div>
          <div *ngIf="selectedGroup === group.id" class="w-2 h-2 bg-blue-500 rounded-full"></div>
        </div>
      </div>
    </div>
  
    <!-- Chat Area -->
    <div class="flex-1 flex flex-col bg-gray-50">
      <!-- Top Navigation -->
      <div class="flex items-center justify-between p-4 bg-white shadow-md">
        <div class="flex items-center space-x-4">
          <button class="text-gray-600 hover:bg-gray-100 p-2 rounded-full transition">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
          </button>
          <h2 class="text-xl font-semibold">{{ selectedGroupName }}</h2>
        </div>
  
        <div class="flex items-center space-x-3">
          <div *ngFor="let user of userIcons" class="text-3xl cursor-pointer"
               [ngClass]="{
                 'ring-2 ring-blue-500 rounded-full': currentUser.name === user.name,
                 'opacity-60 hover:opacity-100': currentUser.name !== user.name
               }"
               (click)="handleUserSelection(user)"
               [title]="user.name">
            {{ user.avatar }}
          </div>
        </div>
      </div>
  
      <!-- Chat Display -->
      <div class="flex-1 overflow-auto p-6 space-y-4">
        <div *ngIf="selectedGroup; else noGroupSelected">
          <div *ngFor="let msg of filteredMessages" class="flex"
               [ngClass]="{ 'justify-end': msg.sender === currentUser.name, 'justify-start': msg.sender !== currentUser.name }">
            <div class="max-w-md p-3 rounded-lg shadow-md"
                 [ngClass]="{ 'bg-blue-500 text-white': msg.sender === currentUser.name, 'bg-white text-gray-800': msg.sender !== currentUser.name }">
              <div class="flex justify-between items-center mb-1">
                <span class="text-xs font-semibold mr-2">{{ msg.sender === currentUser.name ? 'You' : msg.sender }}</span>
                <span class="text-xs opacity-70">{{ formatTimestamp(msg.timestamp) }}</span>
              </div>
              {{ msg.text }}
            </div>
          </div>
        </div>
        <ng-template #noGroupSelected>
          <div class="flex flex-col items-center justify-center h-full text-gray-400 text-center">
            <p class="text-xl">Select a group to start chatting</p>
          </div>
        </ng-template>
      </div>
  
      <!-- Message Input -->
      <div *ngIf="selectedGroup" class="p-4 bg-white border-t">
        <div class="flex space-x-3 items-center">
          <input type="text" [(ngModel)]="message" placeholder="Type a message" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" />
          <button (click)="handleSendMessage()" [disabled]="!message.trim()" class="bg-blue-500 text-white p-2 rounded-full hover:bg-blue-600 disabled:opacity-50 transition">
            Send
          </button>
        </div>
      </div>
    </div>
  </div>

// frontend/src/pages/ChatInterface.tsx
import React, { useState, useEffect } from "react";
import { Users, ArrowLeft, Send, MessageSquare } from "lucide-react";

const groups = [
  { id: "1", name: "Design Team", description: "Creative professionals" },
  { id: "2", name: "Development Team", description: "Tech innovators" },
  { id: "3", name: "Marketing Team", description: "Brand storytellers" },
];

const userIcons = [
  { name: "Emma", avatar: "👩‍💻" },
  { name: "Alex", avatar: "👤" },
  { name: "Sam", avatar: "🧑‍🎨" },
];

const ChatInterface: React.FC = () => {
  const [selectedGroup, setSelectedGroup] = useState<string | null>(null);
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState<
    {
      groupId: string;
      text: string;
      sender: string;
      timestamp: Date;
    }[]
  >([]);
  const [currentUser, setCurrentUser] = useState(userIcons[0]);

  const handleSendMessage = () => {
    if (message.trim() && selectedGroup) {
      setMessages((prev) => [
        ...prev,
        {
          groupId: selectedGroup,
          text: message,
          sender: currentUser.name,
          timestamp: new Date(),
        },
      ]);
      setMessage("");
    }
  };

  const formatTimestamp = (date: Date) => {
    return date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
  };

  return (
    <div className="flex h-screen bg-gray-100 overflow-hidden">
      {/* Sidebar */}
      <div className="w-1/4 bg-white border-r shadow-xl">
        <div className="p-6 bg-gradient-to-r from-blue-600 to-blue-500 text-white">
          <div className="flex items-center space-x-3">
            <MessageSquare size={32} />
            <h2 className="text-2xl font-bold">Group Chat</h2>
          </div>
        </div>

        {groups.map((group) => (
          <div
            key={group.id}
            className={`p-4 cursor-pointer transition-all duration-200 border-l-4 
              ${
                selectedGroup === group.id
                  ? "border-blue-500 bg-blue-50 text-blue-700"
                  : "border-transparent hover:border-gray-300 hover:bg-gray-50"
              }`}
            onClick={() => setSelectedGroup(group.id)}
          >
            <div className="flex justify-between items-center">
              <div>
                <h3 className="font-semibold text-lg">{group.name}</h3>
                <p className="text-sm text-gray-500">{group.description}</p>
              </div>
              {selectedGroup === group.id && (
                <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* Chat Area */}
      <div className="flex-1 flex flex-col bg-gray-50">
        {/* Top Navigation */}
        <div className="flex items-center justify-between p-4 bg-white shadow-md">
          <div className="flex items-center space-x-4">
            <button
              onClick={() => {
                /* Implement actual navigation */
              }}
              className="text-gray-600 hover:bg-gray-100 p-2 rounded-full transition"
            >
              <ArrowLeft />
            </button>
            <h2 className="text-xl font-semibold">
              {selectedGroup
                ? groups.find((g) => g.id === selectedGroup)?.name
                : "Select a Group"}
            </h2>
          </div>

          <div className="flex items-center space-x-3">
            <Users className="text-gray-500" />
            {userIcons.map((user, idx) => (
              <div
                key={idx}
                className={`text-3xl cursor-pointer 
                  ${
                    currentUser.name === user.name
                      ? "ring-2 ring-blue-500 rounded-full"
                      : "opacity-60 hover:opacity-100"
                  }`}
                onClick={() => setCurrentUser(user)}
                title={user.name}
              >
                {user.avatar}
              </div>
            ))}
          </div>
        </div>

        {/* Chat Display */}
        <div className="flex-1 overflow-auto p-6 space-y-4">
          {selectedGroup ? (
            messages
              .filter((msg) => msg.groupId === selectedGroup)
              .map((msg, idx) => (
                <div
                  key={idx}
                  className={`flex ${
                    msg.sender === currentUser.name
                      ? "justify-end"
                      : "justify-start"
                  }`}
                >
                  <div
                    className={`max-w-md p-3 rounded-lg shadow-md ${
                      msg.sender === currentUser.name
                        ? "bg-blue-500 text-white"
                        : "bg-white text-gray-800"
                    }`}
                  >
                    <div className="flex justify-between items-center mb-1">
                      <span className="text-xs font-semibold mr-2">
                        {msg.sender === currentUser.name ? "You" : msg.sender}
                      </span>
                      <span className="text-xs opacity-70">
                        {formatTimestamp(msg.timestamp)}
                      </span>
                    </div>
                    {msg.text}
                  </div>
                </div>
              ))
          ) : (
            <div className="flex flex-col items-center justify-center h-full text-gray-400 text-center">
              <MessageSquare size={64} className="mb-4 opacity-50" />
              <p className="text-xl">Select a group to start chatting</p>
              <p className="text-sm">Choose a team from the sidebar</p>
            </div>
          )}
        </div>

        {/* Message Input */}
        {selectedGroup && (
          <div className="p-4 bg-white border-t">
            <div className="flex space-x-3 items-center">
              <div className="flex-grow">
                <input
                  type="text"
                  value={message}
                  placeholder={`Message ${
                    groups.find((g) => g.id === selectedGroup)?.name
                  }`}
                  onChange={(e) => setMessage(e.target.value)}
                  onKeyPress={(e) => e.key === "Enter" && handleSendMessage()}
                  className="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <button
                onClick={handleSendMessage}
                disabled={!message.trim()}
                className="bg-blue-500 text-white p-2 rounded-full hover:bg-blue-600 disabled:opacity-50 transition"
              >
                <Send />
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ChatInterface;
